$SUITE_VARS$:
  sleep_time: 2.0
  _python_pre: "export PYTHONPATH={{ exp_code_dir }}/utils && . {{ exp_code_dir }}/.venv/bin/activate"
  _python_path: "[% my_run._python_pre %] && {{ exp_code_dir }}/.venv/bin/python"
  cmd_mpspdz: "[% my_run._python_path %] -m  python_utils.scripts.experiment_runner --player-number <PLAYER-ID> --sleep-time [% my_run.sleep_time %]"

  n_parties: 3

  $INCLUDE_VARS$: dataset.yml

  commit_output: False
  convert_ring_bits: 64

  consistency_args:
    abs_path_to_code_dir: "{{ exp_consistency_dir }}"
    hosts_file: "{{ exp_consistency_hosts_file }}"
    pc: kzg
    pp_args: "[% my_run.dataset_info[my_run.mpc.script_args.dataset].max_input_size %]"

  mpc:
    player_0_hostname: "[% exp_host_lst | json_query('[?host_type==`consistency`].private_dns_name') | default(['<UNDEFINED-DNS>'], true) | first %]"
    abs_path_to_code_dir: "{{ exp_code_dir }}"
    player_count: "[% my_run.n_parties %]"

    protocol_setup: "sy-rep-ring-party"
    domain: ring
    compiler_args: [ '-R', '64', '-C', '--budget', '10000', '-D', '-Z', '3' ]
    custom_prime: null



    script_args:

      n_samples: 1
      n_input_parties: "[% my_run.n_parties %]"

      dataset:
        $FACTOR$: [ adult_3p, mnist_full_3party, cifar_alexnet_3party ]

      debug: False
      emulate: False

      batch_size: 128
      n_threads: 16
      audit_trigger_idx: 0
      trunc_pr: False

      round_nearest: False

    stage:
      $FACTOR$: [ compile, run ]


audit_sample_knnshapley:
  n_repetitions: 1
  host_types:
    consistency:
      n: 3
      check_status: True
      init_roles:
        - setup-base
        - setup-consistency
      $CMD$:
        - main: "[% my_run.cmd_mpspdz | replace('<PLAYER-ID>', 0) %]"
        - main: "[% my_run.cmd_mpspdz | replace('<PLAYER-ID>', 1) %]"
        - main: "[% my_run.cmd_mpspdz | replace('<PLAYER-ID>', 2) %]"

  base_experiment:
    mpc:
      script_name: audit_sample_knnshapley


audit_owner_unlearn:
  n_repetitions: 1
  host_types:
    consistency:
      n: 3
      check_status: True
      init_roles:
        - setup-base
        - setup-consistency
      $CMD$:
        - main: "[% my_run.cmd_mpspdz | replace('<PLAYER-ID>', 0) %]"
        - main: "[% my_run.cmd_mpspdz | replace('<PLAYER-ID>', 1) %]"
        - main: "[% my_run.cmd_mpspdz | replace('<PLAYER-ID>', 2) %]"

  base_experiment:
    mpc:
      script_name: audit_owner_unlearn

audit_robustness:
  n_repetitions: 1
  host_types:
    consistency:
      n: 3
      check_status: True
      init_roles:
        - setup-base
        - setup-consistency
      $CMD$:
        - main: "[% my_run.cmd_mpspdz | replace('<PLAYER-ID>', 0) %]"
        - main: "[% my_run.cmd_mpspdz | replace('<PLAYER-ID>', 1) %]"
        - main: "[% my_run.cmd_mpspdz | replace('<PLAYER-ID>', 2) %]"

  base_experiment:
    mpc:
      script_name: audit_robustness


$ETL$: {}