
git_remote_repository:
- repo: "https://github.com/Alfred-hhy/arc.git"
  version: main

prj_id_prefix: "cryptographic-auditing-mpc"

prj_id: "{{ prj_id_prefix }}_{{ does_project_id_suffix }}"

job_n_tries: 10000
job_check_wait_time: 5

etl_minimum_delay_sec: 30

remote:
  dir: "{{ '/cluster/home/' + euler_user + '/doe-suite/' + prj_id + '/' + suite if cloud == 'euler' else '/home/ubuntu' }}"
  results_dir: "{{ '/cluster/scratch/' + euler_user + '/results' if cloud == 'euler' else '/home/ubuntu/results' }}"

exp_code_dir: "{{ remote.dir }}/code"
mpspdz_dir: "{{ exp_code_dir }}/MP-SPDZ"
exp_consistency_dir: "{{ remote.dir }}/code/mpc-consistency"

exp_consistency_hosts_file: "{{ exp_consistency_dir }}/data/vpc"

dataset_dir: "{{ exp_code_dir }}/input_data"

local:
  results_dir: "{{ does_project_dir }}/doe-suite-results"
  designs_dir: "{{ does_config_dir }}/designs"

exp_base:
  aws_region: eu-central-1
  name: frankfurt
  vpc_name: "{{ prj_id }}_vpc_base"
  vpc_cidr_block: 10.100.0.0/16
  vpc_subnet_name: "{{ prj_id }}_subnet_az1"
  vpc_subnet_cidr: 10.100.0.0/24
  sg_name: "{{ prj_id }}_{{ suite | default('') }}_sg"
  sg_desc: "{{ prj_id }} {{ suite | default('') }} security group"
