---


- debug:
    msg: "-> arkworks only"
  tags: [print_action]


- name: Delete hosts file
  file:
    path: "{{ exp_hosts_file }}"
    state: absent

- name: Setup hosts file
  lineinfile:
    path: "{{ exp_hosts_file }}"  #
    line: "{{ private_ip_lookup[item.private_dns_name] }}:8000"
    create: yes
  loop: "{{ hostvars['localhost']['suite_hosts_lst'] }}"
  vars:
    private_ip_lookup: "{{ hostvars['localhost']['ec2_instance_info'] | json_query('instances[*].{key: private_dns_name, value: private_ip_address}') | items2dict }}"

